name: Bug report
description: Create a report to help us improve.

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: eslint-version
    attributes:
      label: What version of ESLint are you using?
      placeholder: 0.0.0
    validations:
      required: true
  - type: input
    id: eslint-version
    attributes:
      label: What version of `eslint-plugin-astro` are you using?
      placeholder: 0.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you do?
      description: |
        Please include a *minimal* reproduction case.
      value: |
        <details>
        <summary>Configuration</summary>

        ```
        <!-- Paste your configuration here -->
        ```
        </details>

        ```astro
        <!-- Paste your code here -->
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to happen?
      description: |
        You can use Markdown in this field.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What actually happened?
      description: |
        Please copy-paste the actual ESLint output. You can use Markdown in this field.
    validations:
      required: true
  - type: textarea
    id: bug-reproduction
    attributes:
      label: Link to Minimal Reproducible Example
      description: |
        Create a minimal reproduction of the problem. **A minimal reproduction is required** so that others can help debug your issue. If a report is vague (e.g. just a generic error message) and has no reproduction, it may be closed.  
        You can also use the [Online Demo](https://ota-meshi.github.io/eslint-plugin-astro/playground/).
      placeholder: |
        https://github.com/[your]/[repo]
        or
        https://ota-meshi.github.io/eslint-plugin-astro/playground/#[hash]
    validations:
      required: true
