import path from "path"
import renderRulesTableContent from "./render-rules-table"
import { formatAndSave } from "./lib/utils"

const currentFileName = path.basename(__filename)
const rulesPageFilePath = path.resolve(
  __dirname,
  "../docs2/src/content/docs/rules.mdx",
)

const rulesFrontMatter = `---
title: Rules
---`

const rulesMd = `# Available Rules

The \`--fix\` option on the [command line](https://eslint.org/docs/user-guide/command-line-interface#fixing-problems) automatically fixes problems reported by rules which have a wrench 🔧 below.
The rules with the following star ⭐ are included in the \`plugin:astro/recommended\` config.

> Doesn't the rule you want exist? [Share your idea of that rule with us](https://github.com/ota-meshi/eslint-plugin-astro/issues/new?template=new_rule_request.yml).

${renderRulesTableContent()}
[eslint-plugin-jsx-a11y]: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y`

const rulesMdx = `${rulesFrontMatter}
{/* This file is automatically generated in tools/${currentFileName}, do not change! */}
${rulesMd}
`

void formatAndSave(rulesPageFilePath, rulesMdx)
